### ISSUE TITLE
express deprecated res.json(status, obj)

### ISSUE THREAD

**Issue by joshuamabina** [lykmapipo/express-respond#10]
npm advises to use, instead:

```js
res.status(status).json(obj)
```

Using express `^4.15.3`.

**Comment by lykmapipo** [comment]
@joshuamabina Sure. [Check](https://github.com/lykmapipo/express-respond/blob/bb24eba1567c3c48f8e1ded6cf8465787b2c6935/index.js#L40) the library have been using the format below to compose response.

```js
response.status(status);
response.json(data);
```
