### ISSUE TITLE
Support default response body

### ISSUE THREAD

**Issue by joshuamabina** [lykmapipo/express-respond#7]
In the case, respond utility is invoked without arguments, example:

```js
res.badRequest();
```

It would be nice to get:

```js
{
	message: "Bad Request",
	statusCode: 400,
}
```

Instead of an empty object **(currently)**:

```
{}
```

**Comment by joshuamabina** [comment]
After experimenting, calling, `res.badRequest` and expecting defaults is not useful to the api consumer.

A useful approach would be, as an example:

```js
// invoke
const error = new Error('Bad Request');
res.badRequest(error);

// get
{
   message: 'Bad Request',
   statusCode: 400
}
```

The downfall of the implementation is it makes an assumption that the api consumer is going to be pragmatic enough to create an error object which will then be used with the to invoke bad request response. Maybe you can advise.

**Comment by lykmapipo** [comment]
@joshuamabina Sure. I can make default response body a feature to opt for using options.
